class PageMapper{
    static keyToIndex= {
        "Goodbye Sphere":1,
        "The ground is red!":2,
        "The ground is checkered!":3,
        "Yeti on the dance floor!":4,
        "Move that camera!":5,
        "CreateScene Playground":6,
        "Getting Started First Scene Playground.":7,
        "First Model on a Web Page":8,
        "Load a model into a scene.":9,
        "Load multiple models into a scene.":10,
        
        "Load a model into a scene and modify their position after loading completes.":11,
        "Import a Model Setup":12,
        "Code a Model Setup":13,
        "A playground showing how to add a basic ground plane to your scene.":14,
        "A playground showing how to adjust the position of the box.":15,
        "A playground showing how easy it is to add sound to your scene.":16,
        "Set an interval to play a sound every 3 seconds.":17,
        "A playground demonstrating different ways to position a mesh in your scene.":18,
        "A playground demonstrating how to rotate a mesh in your scene.":19,
        "":20,
        
        "":21,
        "":22,
        "":23,
        "":24,
        "":25,
        "":26,
        "":27,
        "":28,
        "":29,
        "":30,
        
        "":31,
        "":32,
        "":33,
        "":34,
        "":35,
        "":36,
        "":37,
        "":38,
        "":39,
        "":40,
        
        "":41,
        "":42,
        "":43,
        "":44,
        "":45,
        "":46,
        "":47,
        "":48,
        "":49,
        "":50,
        
        "":51,
        "":52,
        "":53,
        "":54,
        "":55,
        "":56,
        "":57,
        "":58,
        "":59,
        "":60,
        
        "":61,
        "":62,
        "":63,
        "":64,
        "":65,
        "":66,
        "":67,
        "":68,
        "":69,
        "":70,
        
        
    };
}